
GET http://localhost:3000/contacts/

###

GET http://localhost:3000/contacts/1/

###

POST http://localhost:3000/contacts/
Content-Type: application/json

{
  
  "contactId": 1,
  "name": "Bhavani",
  "email": "bhavanib99@gmail.com",
  "phoneno":"9123456789",
  "address": "Hyderabad"
}

###

PUT http://localhost:3000/contacts/5/
Content-Type: application/json

{
  "contactId": 5,
  "name": "Vinay",
  "email": "vinaym14@gmail.com",
  "phoneno":"9223344770",
  "address": "Hyderabad"
}

###

DELETE http://localhost:3000/contacts/3/

###

GET http://localhost:3000/contacts/1/
